import { db } from '@/db';
import { scans, findings } from '@/db/schema';
import { eq, and, desc } from 'drizzle-orm';
import { notFound } from 'next/navigation';
import { ScoreCircle } from '@/components/score-circle';
import { FindingCard } from '@/components/finding-card';
import type { Metadata } from 'next';

interface Props {
  params: Promise<{ owner: string; repo: string }>;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { owner, repo } = await params;
  const [scan] = await db.select().from(scans)
    .where(and(eq(scans.repoOwner, owner), eq(scans.repoName, repo), eq(scans.status, 'complete')))
    .orderBy(desc(scans.createdAt)).limit(1);

  if (!scan) return { title: `${owner}/${repo} — git.exposed` };

  return {
    title: `${scan.grade} (${scan.score}/100) — ${owner}/${repo} — git.exposed`,
    description: `Vibe Safety Score: ${scan.score}/100 (${scan.grade}). ${scan.findingsCount} issues found.`,
    openGraph: {
      title: `${owner}/${repo} scored ${scan.grade} on git.exposed`,
      description: `${scan.findingsCount} security issues found. Vibe Safety Score: ${scan.score}/100.`,
    },
  };
}

export default async function ReportPage({ params }: Props) {
  const { owner, repo } = await params;

  const [scan] = await db.select().from(scans)
    .where(and(eq(scans.repoOwner, owner), eq(scans.repoName, repo), eq(scans.status, 'complete')))
    .orderBy(desc(scans.createdAt)).limit(1);

  if (!scan) notFound();

  const scanFindings = await db.select().from(findings).where(eq(findings.scanId, scan.id));

  return (
    <div className="min-h-screen bg-slate-950 text-slate-200">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <header className="text-center mb-10">
          <h1 className="text-lg text-slate-400 mb-6">git.exposed</h1>
          <ScoreCircle grade={scan.grade!} score={scan.score!} />
          <p className="text-sm text-slate-500 mt-4">
            {scanFindings.length} issues found &middot; Scanned {scan.createdAt.toISOString().slice(0, 10)}
          </p>
          <p className="text-base text-slate-300 mt-2 font-mono">{owner}/{repo}</p>
        </header>

        <div className="flex gap-2 justify-center flex-wrap mb-8">
          {(['critical', 'high', 'medium', 'low'] as const).map((sev) => {
            const count = scanFindings.filter((f) => f.severity === sev).length;
            if (count === 0) return null;
            const colors: Record<string, string> = { critical: 'bg-red-600', high: 'bg-orange-600', medium: 'bg-yellow-600', low: 'bg-blue-600' };
            return (
              <span key={sev} className={`${colors[sev]} text-white text-xs font-semibold px-3 py-1 rounded-full`}>
                {count} {sev}
              </span>
            );
          })}
        </div>

        {scanFindings.length === 0 ? (
          <div className="text-center py-12 text-green-500">
            <h2 className="text-2xl font-bold mb-2">No issues found!</h2>
            <p className="text-slate-400">Your app passed all checks. Nice vibes.</p>
          </div>
        ) : (
          <div className="space-y-3">
            {scanFindings.map((f) => (
              <FindingCard
                key={f.id}
                severity={f.severity}
                title={f.title}
                description={f.description}
                file={f.file}
                line={f.line}
              />
            ))}
          </div>
        )}

        <footer className="text-center text-slate-600 text-xs mt-12 pt-6 border-t border-slate-800">
          Generated by <a href="https://git.exposed" className="text-slate-500 hover:text-slate-300">git.exposed</a> — Is your code exposed?
        </footer>
      </div>
    </div>
  );
}
