import { cn } from '@/lib/utils';
import { db } from '@repo/shared/db';
import { scans, findings } from '@repo/shared/db/schema';
import { eq, and, desc } from 'drizzle-orm';
import { ViewTransition } from 'react';
import { ScoreCircle } from '@/components/score-circle';
import { FindingCard } from '@/components/finding-card';
import { CopyButton } from '@/components/copy-button';
import { AutoScan } from '@/components/auto-scan';
import { BackLink } from '@/components/back-link';
import type { Metadata } from 'next';

interface Props {
  params: Promise<{ owner: string; repo: string }>;
}

function PageShell({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-dvh bg-background text-slate-200">
      <div className="max-w-3xl mx-auto px-6 py-12">
        {children}
        <footer className="text-center text-slate-400 text-xs mt-10 pt-6 border-t border-ds-border/30">
          Generated by <a href="https://git.exposed" className="text-slate-400 hover:text-slate-300" target="_blank" rel="noopener">git.exposed</a> - Is your code exposed?
        </footer>
      </div>
    </div>
  );
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { owner, repo } = await params;
  const [scan] = await db.select().from(scans)
    .where(and(eq(scans.repoOwner, owner), eq(scans.repoName, repo), eq(scans.status, 'complete')))
    .orderBy(desc(scans.createdAt)).limit(1);

  if (!scan) return { title: `${owner}/${repo} - git.exposed` };

  const pageTitle = `${scan.grade} (${scan.score}/100) - ${owner}/${repo} - git.exposed`;
  const summary = `${scan.findingsCount} security issues found. Vibe Safety Score: ${scan.score}/100.`;

  return {
    title: pageTitle,
    description: `Vibe Safety Score: ${scan.score}/100 (${scan.grade}). ${scan.findingsCount} issues found.`,
    openGraph: {
      title: `${owner}/${repo} scored ${scan.grade} on git.exposed`,
      description: summary,
      siteName: 'git.exposed',
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title: `${owner}/${repo} scored ${scan.grade} on git.exposed`,
      description: summary,
    },
  };
}

export default async function ReportPage({ params }: Props) {
  const { owner, repo } = await params;

  const [scan] = await db.select().from(scans)
    .where(and(eq(scans.repoOwner, owner), eq(scans.repoName, repo), eq(scans.status, 'complete')))
    .orderBy(desc(scans.createdAt)).limit(1);

  if (!scan) {
    return (
      <ViewTransition
        enter={{ 'nav-forward': 'nav-forward', default: 'none' }}
        exit={{ 'nav-back': 'nav-back', default: 'none' }}
        default="none"
      >
        <PageShell><AutoScan owner={owner} repo={repo} /></PageShell>
      </ViewTransition>
    );
  }

  const scanFindings = await db.select().from(findings).where(eq(findings.scanId, scan.id));

  return (
    <ViewTransition
      enter={{ 'nav-forward': 'nav-forward', default: 'none' }}
      exit={{ 'nav-back': 'nav-back', default: 'none' }}
      default="none"
    >
      <div className="min-h-dvh bg-background text-slate-200">
        <div className="max-w-3xl mx-auto px-6 py-12">
          <header className="text-center mb-10">
            <ScoreCircle grade={scan.grade!} score={scan.score!} />
            <p className="text-sm text-slate-400 mt-4">
              {scanFindings.length} issues found &middot; Scanned {scan.createdAt.toISOString().slice(0, 10)}
            </p>
            <p className="text-base text-slate-300 mt-2 font-mono">{owner}/{repo}</p>
          </header>

          <div className="flex gap-2 justify-center flex-wrap mb-8">
            {(['critical', 'high', 'medium', 'low'] as const).map((sev) => {
              const count = scanFindings.filter((f) => f.severity === sev).length;
              if (count === 0) return null;
              const colors: Record<string, string> = { critical: 'bg-red-700', high: 'bg-orange-700', medium: 'bg-yellow-700', low: 'bg-blue-700' };
              return (
                <span key={sev} className={cn(colors[sev], 'text-white text-xs font-semibold px-3 py-1 rounded-full')}>
                  {count} {sev}
                </span>
              );
            })}
          </div>

          {scanFindings.length === 0 ? (
            <div className="text-center py-12 text-green-500">
              <h2 className="text-2xl font-bold mb-2">No issues found!</h2>
              <p className="text-slate-400">Your app passed all checks. Ship with confidence.</p>
            </div>
          ) : (
            <div className="space-y-3">
              {scanFindings.map((f) => (
                <FindingCard
                  key={f.id}
                  severity={f.severity}
                  title={f.title}
                  description={f.description}
                  file={f.file}
                  line={f.line}
                />
              ))}
            </div>
          )}

          <div className="mt-10 p-5 rounded-lg border border-ds-border/30 bg-ds-muted/50">
            <div className="flex items-center justify-between mb-4">
              <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Share this report</span>
              <CopyButton text={`https://git.exposed/${owner}/${repo}`} label="Copy link" />
            </div>
            <div className="space-y-3">
              <div>
                <span className="text-[0.65rem] text-slate-400 block mb-1">README badge</span>
                <div className="flex items-center gap-2">
                  <code className="text-xs text-slate-300 bg-slate-800 px-3 py-2 rounded flex-1 overflow-x-auto font-mono">
                    {`![git.exposed](https://git.exposed/badge/${owner}/${repo})`}
                  </code>
                  <CopyButton text={`![git.exposed](https://git.exposed/badge/${owner}/${repo})`} label="Copy" />
                </div>
              </div>
            </div>
          </div>

          <div className="text-center mt-8">
            <BackLink />
          </div>

          <footer className="text-center text-slate-400 text-xs mt-10 pt-6 border-t border-ds-border/30">
            Generated by <a href="https://git.exposed" className="text-slate-400 hover:text-slate-300" target="_blank" rel="noopener">git.exposed</a> - Is your code exposed?
          </footer>
        </div>
      </div>
    </ViewTransition>
  );
}
