import { db } from '@repo/shared/db';
import { scans, findings, accounts, subscriptions } from '@repo/shared/db/schema';
import { eq, and, desc } from 'drizzle-orm';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { ScoreCircle } from '@/components/score-circle';
import { FindingCard } from '@/components/finding-card';
import { CopyButton } from '@/components/copy-button';
import { FixButton } from '@/components/fix-button';
import { AutoScan } from '@/components/auto-scan';
import { PrivateRepoGate } from '@/components/private-repo-gate';
import { auth } from '@/lib/auth';
import type { Metadata } from 'next';

interface Props {
  params: Promise<{ owner: string; repo: string }>;
}

async function getRepoVisibility(
  owner: string,
  repo: string,
  token?: string | null,
): Promise<'public' | 'private' | 'not_found'> {
  try {
    const headers: Record<string, string> = { Accept: 'application/vnd.github+json' };
    if (token) headers.Authorization = `Bearer ${token}`;
    const res = await fetch(`https://api.github.com/repos/${owner}/${repo}`, { headers });
    if (!res.ok) return 'not_found';
    const data = await res.json();
    return data.private ? 'private' : 'public';
  } catch {
    return 'not_found';
  }
}

function PageShell({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-dvh bg-background text-slate-200">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <header className="text-center mb-10">
          <h1 className="text-lg text-slate-400 mb-6">git.exposed</h1>
        </header>
        {children}
        <footer className="text-center text-slate-400 text-xs mt-10 pt-6 border-t border-ds-border/30">
          Generated by <a href="https://git.exposed" className="text-slate-400 hover:text-slate-300" target="_blank" rel="noopener">git.exposed</a> - Is your code exposed?
        </footer>
      </div>
    </div>
  );
}

function CenteredShell({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-dvh bg-background text-slate-200 flex items-center justify-center px-6">
      {children}
    </div>
  );
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { owner, repo } = await params;
  const [scan] = await db.select().from(scans)
    .where(and(eq(scans.repoOwner, owner), eq(scans.repoName, repo), eq(scans.status, 'complete')))
    .orderBy(desc(scans.createdAt)).limit(1);

  if (!scan) return { title: `${owner}/${repo} - git.exposed` };

  const pageTitle = `${scan.grade} (${scan.score}/100) - ${owner}/${repo} - git.exposed`;
  const summary = `${scan.findingsCount} security issues found. Vibe Safety Score: ${scan.score}/100.`;

  return {
    title: pageTitle,
    description: `Vibe Safety Score: ${scan.score}/100 (${scan.grade}). ${scan.findingsCount} issues found.`,
    openGraph: {
      title: `${owner}/${repo} scored ${scan.grade} on git.exposed`,
      description: summary,
      siteName: 'git.exposed',
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title: `${owner}/${repo} scored ${scan.grade} on git.exposed`,
      description: summary,
    },
  };
}

export default async function ReportPage({ params }: Props) {
  const { owner, repo } = await params;

  const [scan] = await db.select().from(scans)
    .where(and(eq(scans.repoOwner, owner), eq(scans.repoName, repo), eq(scans.status, 'complete')))
    .orderBy(desc(scans.createdAt)).limit(1);

  if (!scan) {
    // No scan exists — determine what to show based on repo visibility
    const visibility = await getRepoVisibility(owner, repo);

    if (visibility === 'public') {
      return <PageShell><AutoScan owner={owner} repo={repo} /></PageShell>;
    }

    // Repo returned 404 — could be private or nonexistent
    const session = await auth();

    if (!session?.user?.id) {
      return <CenteredShell><PrivateRepoGate owner={owner} repo={repo} state="sign-in" /></CenteredShell>;
    }

    // User is signed in — verify with their GitHub token
    const [account] = await db.select()
      .from(accounts)
      .where(and(eq(accounts.userId, session.user.id), eq(accounts.provider, 'github')))
      .limit(1);

    if (account?.access_token) {
      const authVisibility = await getRepoVisibility(owner, repo, account.access_token);
      if (authVisibility !== 'not_found') {
        // Repo exists — check subscription for private repos
        if (authVisibility === 'public') {
          return <PageShell><AutoScan owner={owner} repo={repo} /></PageShell>;
        }
        const [sub] = await db.select()
          .from(subscriptions)
          .where(and(eq(subscriptions.userId, session.user.id), eq(subscriptions.status, 'active')))
          .limit(1);
        if (sub) {
          return <PageShell><AutoScan owner={owner} repo={repo} /></PageShell>;
        }
        return <CenteredShell><PrivateRepoGate owner={owner} repo={repo} state="upgrade" /></CenteredShell>;
      }
    }

    // Repo truly doesn't exist
    notFound();
  }

  const scanFindings = await db.select().from(findings).where(eq(findings.scanId, scan.id));

  // Check Pro status for Fix button
  const session = await auth();
  let isPro = false;
  if (session?.user?.id) {
    const [sub] = await db.select()
      .from(subscriptions)
      .where(and(eq(subscriptions.userId, session.user.id), eq(subscriptions.status, 'active')))
      .limit(1);
    isPro = !!sub;
  }

  return (
    <div className="min-h-dvh bg-background text-slate-200">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <header className="text-center mb-10">
          <h1 className="text-lg text-slate-400 mb-6">git.exposed</h1>
          <ScoreCircle grade={scan.grade!} score={scan.score!} />
          <p className="text-sm text-slate-400 mt-4">
            {scanFindings.length} issues found &middot; Scanned {scan.createdAt.toISOString().slice(0, 10)}
          </p>
          <p className="text-base text-slate-300 mt-2 font-mono">{owner}/{repo}</p>
        </header>

        <div className="flex gap-2 justify-center flex-wrap mb-8">
          {(['critical', 'high', 'medium', 'low'] as const).map((sev) => {
            const count = scanFindings.filter((f) => f.severity === sev).length;
            if (count === 0) return null;
            const colors: Record<string, string> = { critical: 'bg-red-700', high: 'bg-orange-700', medium: 'bg-yellow-700', low: 'bg-blue-700' };
            return (
              <span key={sev} className={`${colors[sev]} text-white text-xs font-semibold px-3 py-1 rounded-full`}>
                {count} {sev}
              </span>
            );
          })}
        </div>

        {scanFindings.length === 0 ? (
          <div className="text-center py-12 text-green-500">
            <h2 className="text-2xl font-bold mb-2">No issues found!</h2>
            <p className="text-slate-400">Your app passed all checks. Ship with confidence.</p>
          </div>
        ) : (
          <div className="space-y-3">
            {scanFindings.map((f) => (
              <FindingCard
                key={f.id}
                severity={f.severity}
                title={f.title}
                description={f.description}
                file={f.file}
                line={f.line}
              />
            ))}
          </div>
        )}

        {scanFindings.length > 0 && (
          <FixButton
            scanId={scan.id}
            findings={scanFindings.map((f) => ({
              id: f.id,
              severity: f.severity,
              title: f.title,
              file: f.file,
            }))}
            isPro={isPro}
          />
        )}

        <div className="mt-10 p-5 rounded-lg border border-ds-border/30 bg-ds-muted/50">
          <div className="flex items-center justify-between mb-4">
            <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Share this report</span>
            <CopyButton text={`https://git.exposed/${owner}/${repo}`} label="Copy link" />
          </div>
          <div className="space-y-3">
            <div>
              <span className="text-[0.65rem] text-slate-400 block mb-1">README badge</span>
              <div className="flex items-center gap-2">
                <code className="text-xs text-slate-300 bg-slate-800 px-3 py-2 rounded flex-1 overflow-x-auto font-mono">
                  {`![git.exposed](https://git.exposed/badge/${owner}/${repo})`}
                </code>
                <CopyButton text={`![git.exposed](https://git.exposed/badge/${owner}/${repo})`} label="Copy" />
              </div>
            </div>
          </div>
        </div>

        <div className="text-center mt-8">
          <Link href="/" className="text-red-500 hover:text-red-400 font-semibold text-sm">
            Scan another repo &rarr;
          </Link>
        </div>

        <footer className="text-center text-slate-400 text-xs mt-10 pt-6 border-t border-ds-border/30">
          Generated by <a href="https://git.exposed" className="text-slate-400 hover:text-slate-300" target="_blank" rel="noopener">git.exposed</a> - Is your code exposed?
        </footer>
      </div>
    </div>
  );
}
