import { db } from "@repo/shared/db";
import { findings, fixJobs } from "@repo/shared/db/schema";
import { eq, inArray } from "drizzle-orm";
import { downloadRepo } from "@repo/shared/github";
import { Octokit } from "@octokit/rest";
import { CopilotClient } from "@github/copilot-sdk";
import { rm, readFile } from "node:fs/promises";
import { exec } from "node:child_process";
import { promisify } from "node:util";
import path from "node:path";

const execAsync = promisify(exec);

export async function runFix(
  jobId: string,
  owner: string,
  repo: string,
  findingIds: string[],
  accessToken: string,
) {
  let dir: string | undefined;

  try {
    await db
      .update(fixJobs)
      .set({ status: "running" })
      .where(eq(fixJobs.id, jobId));

    // Fetch finding details
    const targetFindings = await db
      .select()
      .from(findings)
      .where(inArray(findings.id, findingIds));

    if (targetFindings.length === 0) {
      throw new Error("No findings found for the given IDs");
    }

    // Download repo
    dir = await downloadRepo(owner, repo);

    // Initialize git to track changes made by the agent
    await execAsync(
      'git init && git add -A && git commit -m "base" --allow-empty',
      { cwd: dir },
    );

    // Build the fix prompt
    const findingDescriptions = targetFindings
      .map(
        (f, i) =>
          `${i + 1}. [${f.severity.toUpperCase()}] ${f.title}\n   File: ${f.file}${f.line ? `:${f.line}` : ""}\n   ${f.description}`,
      )
      .join("\n\n");

    const prompt = `Fix the following security vulnerabilities in this repository. Make minimal, targeted changes. Do not refactor unrelated code.\n\n${findingDescriptions}`;

    // Run Copilot SDK agent with BYOK (Anthropic key)
    const client = new CopilotClient();
    const session = await client.createSession({
      model: "claude-sonnet-4.5",
      workingDirectory: dir,
      systemMessage: {
        content:
          "You are a security engineer. Fix the specified vulnerabilities with minimal code changes. Only modify what is necessary to resolve each issue. Do not add comments explaining the fix unless the code would be unclear without them.",
      },
    });

    await session.sendAndWait({ prompt });
    await client.stop();

    // Detect changed files
    await execAsync("git add -A", { cwd: dir });
    const { stdout: diffOutput } = await execAsync(
      "git diff --cached --name-only",
      { cwd: dir },
    );
    const changedFiles = diffOutput.trim().split("\n").filter(Boolean);

    if (changedFiles.length === 0) {
      throw new Error("Copilot agent did not produce any file changes");
    }

    // Create branch and PR via Octokit
    const octokit = new Octokit({ auth: accessToken });

    const { data: repoData } = await octokit.repos.get({ owner, repo });
    const defaultBranch = repoData.default_branch;
    const { data: refData } = await octokit.git.getRef({
      owner,
      repo,
      ref: `heads/${defaultBranch}`,
    });
    const baseSha = refData.object.sha;

    const branchName = `fix/git-exposed-${jobId.slice(0, 8)}`;
    await octokit.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${branchName}`,
      sha: baseSha,
    });

    // Commit each changed file to the new branch
    for (const file of changedFiles) {
      const content = await readFile(path.join(dir, file), "utf-8");
      const contentBase64 = Buffer.from(content).toString("base64");

      let fileSha: string | undefined;
      try {
        const { data } = await octokit.repos.getContent({
          owner,
          repo,
          path: file,
          ref: defaultBranch,
        });
        if ("sha" in data) fileSha = data.sha;
      } catch {
        // New file
      }

      await octokit.repos.createOrUpdateFileContents({
        owner,
        repo,
        path: file,
        message: `fix: resolve security vulnerability in ${file}`,
        content: contentBase64,
        branch: branchName,
        ...(fileSha && { sha: fileSha }),
      });
    }

    // Create PR
    const prTitle = `fix: resolve ${targetFindings.length} security ${targetFindings.length === 1 ? "issue" : "issues"} found by git.exposed`;
    const prBody = [
      "## Security Fixes",
      "",
      "This PR was automatically generated by [git.exposed](https://git.exposed) to fix the following issues:",
      "",
      ...targetFindings.map(
        (f) =>
          `- **[${f.severity.toUpperCase()}]** ${f.title} - \`${f.file}${f.line ? `:${f.line}` : ""}\``,
      ),
      "",
      "---",
      "*Review these changes carefully before merging.*",
    ].join("\n");

    const { data: pr } = await octokit.pulls.create({
      owner,
      repo,
      title: prTitle,
      body: prBody,
      head: branchName,
      base: defaultBranch,
    });

    await db
      .update(fixJobs)
      .set({
        status: "complete",
        prUrl: pr.html_url,
        completedAt: new Date(),
      })
      .where(eq(fixJobs.id, jobId));
  } catch (error) {
    console.error(
      "Fix job failed:",
      error instanceof Error ? error.message : "Unknown error",
    );
    await db
      .update(fixJobs)
      .set({
        status: "failed",
        error: error instanceof Error ? error.message : "Unknown error",
        completedAt: new Date(),
      })
      .where(eq(fixJobs.id, jobId));
  } finally {
    if (dir) await rm(dir, { recursive: true, force: true }).catch(() => {});
  }
}
